description = "Instituto Social Acadêmicos Iluminarte"
homepage = ""
license = "MIT"
licenselink = "https://github.com/Iluminarte/site/blob/development/license.md"
min_version = 0.26
name = "iluminarte-site"
tags = ["iluminarte", "blank", "clean", "developer", "empty", "minimal", "minimalist", "simple", "starter", "theme"]

[author]
homepage = "https://github.com/marcker"
name = "marcker"
